name: QA Tests Pipeline
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman + HTML Reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Postman tests
        run: newman run QA_Demo_Collection.json -r cli,html --reporter-html-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: report.html
